name: data_table_2
description: In-place substitute for Flutter's DataTable and PaginatedDataTable with fixed/sticky headers and few extra features
version: 2.4.2
homepage: https://github.com/maxim-saplin/data_table_2
repository: https://github.com/maxim-saplin/data_table_2

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter: 
    sdk: flutter
  async: ^2.8.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  vector_math: ^2.1.4
  intl: ^0.18.1
  flutter_lints: ^2.0.1

screenshots:
  - description: 'DataTable2 with fixed top row and left column and customized styling'
    path: screenshots/fixed_row_col.png
